### ISSUE TITLE
Don't depend on "@bendrucker/synthetic-dom-events"

### ISSUE THREAD

**Issue by chrisinajar** [bendrucker/dispatch-event#2]
Certain environments hate this style package, we should just publish a proper module and swap out the dependency for that.

**Comment by bendrucker** [comment]
What environments? It's just a published fork so I'm hesitant to publish a whole new module when scoped modules work so well for this.

**Comment by chrisinajar** [comment]
npm 1.x (not really important) and npmjs.org's module demonstrator built into their site

**Comment by bendrucker** [comment]
Submitted a bug report via email to Tonic about their tool. I'd rather keep using public scoped packages and they should support it.

**Comment by bendrucker** [comment]
> Unfortunately, npm doesn't provide a public feed for scoped packages. We have some ideas on how we can work around this, but haven't yet had the chance to implement them. Sorry about that.

Unfortunate, but I'm going to stick to using scoped packages for forks.
